//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;

namespace Trasuanhom15.Models
{
    public  class AdminUser
    {
        [Required]
        //So dien thoai
        public int ID { get; set; }
        [Required]
        public string NameUser { get; set; }
        //[Required]
        public string RoleUser { get; set; }
        [Required]
        public string PasswordUser { get; set; }
    }
}
